### ISSUE TITLE
Use drizzle 

### ISSUE THREAD

**Issue by shiroyasha9** [SkTomsi/splitso#1]
because why not
<br/>
<br/>
<br/>
<br/>
jk jk 
<br/>
<br/>
<br/>
<br/>
<br/>

it's superior 
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

jk jk 
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

am i though?

**Comment by SkTomsi** [comment]
done, ser
